source: src
destination: public_html

url: http://pannotia.local.dev:8888

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "main"
      crumbs: []
      crumbTitles: []
  -
    scope:
      path: "setting/cosmology/planes"
      type: "pages"
    values:
      crumbs: [setting, cosmology]
      crumbTitles: [Setting, Cosmology]
