# Where things are
source:      ./src
destination: ./dist
plugins:     ./plugins
layouts:     ./src/_layouts
data_source: ./src/_data

url: http://chimericdream.github.io/worldofpannotia.com

# Handling Reading
safe:         false
include:      [".htaccess", ".nojekyll"]
exclude:      ["_backup", "nbproject"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    8888
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      America/Chicago

quiet:    false

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: ["tables", "superscript", "underline", "highlight"]

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style