collections:
  organizations:
    output:    true
    permalink: /setting/politics/organizations/:path/

defaults:
  - scope:
      path: ""
      type: "organizations"
    values:
      layout:        "setting/politics/organization"
      organization:
        members:     ""
        description: ""
        history:     ""
        structure:   ""
        leader:      ""
        leaderBio:   ""