collections:
  psicrowns:
    output:    true
    permalink: /equipment/psionic-items/psicrowns/:path/

defaults:
  - scope:
      path: ""
      type: psicrowns
    values:
      layout: "equipment/psionic-items/psicrown"
      crumbs: [equipment, psionic-items, psicrowns]
      crumbTitles: [Equipment, Psionic Items, Psicrowns]
      item:
        shortDesc: ""
        aura: ""
        manifesterLevel: ""
        prerequisites:
          feats: []
          powers: []
          special: []
        marketPrice: 0
        marketPriceSpecial: ""
        costToCreate:
          gp: 0
          xp: 0
        costToCreateSpecial: ""
        weight: ""
        description: ""
