collections:
  epic_rods:
    output:    true
    permalink: /equipment/epic-magic-items/rods/:path/

defaults:
  - scope:
      path: ""
      type: epic_rods
    values:
      layout: "equipment/magic-items/rod"
      crumbs: [equipment, epic-magic-items, rods]
      crumbTitles: [Equipment, Epic Magic Items, Rods]
      item:
        shortDesc: ""
        aura: ""
        casterLevel: ""
        prerequisites:
          feats: []
          spells: []
          special: []
        marketPrice: 0
        marketPriceSpecial: ""
        costToCreate:
          gp: 0
          xp: 0
        costToCreateSpecial: ""
        weight: ""
        description: ""
