collections:
  artifacts:
    output:    true
    permalink: /equipment/artifacts/:path/

defaults:
  - scope:
      path: ""
      type: artifacts
    values:
      layout: "equipment/artifact"
      crumbs:        [equipment, artifacts]
      crumbTitles:   [Equipment, Artifacts]
      activeSection: "equipment/artifacts"
      artifact:
        type: "minor"
        shortDesc: ""
        aura: ""
        casterLevel: ""
        manifesterLevel: ""
        weight: ""
        description: ""
