collections:
  cursed_items:
    output:    true
    permalink: /equipment/cursed-items/:path/

defaults:
  - scope:
      path: ""
      type: cursed_items
    values:
      layout: "equipment/magic-items/wondrous-item"
      crumbs: [equipment, cursed-items]
      crumbTitles: [Equipment, Cursed Items]
      item:
        shortDesc: ""
        aura: ""
        casterLevel: ""
        manifesterLevel: ""
        prerequisites:
          feats: []
          powers: []
          spells: []
          special: []
        slot: ""
        marketPrice: 0
        marketPriceSpecial: ""
        costToCreate:
          gp: 0
          xp: 0
        costToCreateSpecial: ""
        weight: ""
        description: ""
