collections:
  special_abilities:
    output:    true
    permalink: /game-rules/adventuring/special-abilities/:path/

defaults:
  - scope:
      path: ""
      type: special_abilities
    values:
      layout:      "game-rules/adventuring/special-ability"
      crumbs:      [game-rules, adventuring]
      crumbTitles: [Game Rules, Adventuring]
