collections:
  staffs:
    output:    true
    permalink: /equipment/magic-items/staffs/:path/

defaults:
  - scope:
      path: ""
      type: staffs
    values:
      layout: "equipment/magic-items/staff"
      crumbs: [equipment, magic-items, staffs]
      crumbTitles: [Equipment, Magic Items, Staffs]
      item:
        shortDesc: ""
        aura: ""
        casterLevel: ""
        manifesterLevel: ""
        prerequisites:
          feats: []
          powers: []
          spells: []
          special: []
        marketPrice: 0
        marketPriceSpecial: ""
        costToCreate:
          gp: 0
          xp: 0
        costToCreateSpecial: ""
        weight: ""
        description: ""
