collections:
  staffs:
    output:    true
    permalink: /equipment/magic-items/staffs/:path/

defaults:
  - scope:
      path: ""
      type: staffs
    values:
      layout: "equipment/magic-items/staff"
      item:
        shortDesc: ""
        aura: ""
        casterLevel: ""
        prerequisites:
          feats: []
          spells: []
          special: []
        marketPrice: 0
        marketPriceSpecial: ""
        costToCreate:
          gp: 0
          xp: 0
        costToCreateSpecial: ""
        weight: ""
        description: ""
