collections:
  specific_magic_weapons:
    output:    true
    permalink: /equipment/magic-items/weapons/specific/:path/

defaults:
  - scope:
      path: ""
      type: specific_magic_weapons
    values:
      layout: "equipment/magic-items/wondrous-item"
      crumbs: [equipment, magic-items, weapons]
      crumbTitles: [Equipment, Magic Items, Weapons]
      item:
        shortDesc: ""
        aura: ""
        casterLevel: ""
        prerequisites:
          feats: []
          spells: []
          special: []
        slot: ""
        marketPrice: 0
        marketPriceSpecial: ""
        costToCreate:
          gp: 0
          xp: 0
        costToCreateSpecial: ""
        weight: ""
        description: ""
